# Generated by Django 3.1.7 on 2021-03-19 06:22

import api_basic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0005_auto_20210319_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, upload_to=api_basic.models.image_upload_path),
        ),
    ]
