# Generated by Django 3.1.7 on 2021-03-21 07:34

import api_basic.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_basic', '0007_auto_20210319_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('taskName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('originalVideo', models.FileField(upload_to=api_basic.models.video_upload_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
