# Generated by Django 3.1.7 on 2021-03-21 08:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_basic', '0008_usertask'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together={('user', 'taskName')},
        ),
    ]
