# Generated by Django 3.1.7 on 2021-03-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0009_auto_20210321_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertask',
            name='taskName',
            field=models.CharField(max_length=100),
        ),
    ]
