# Generated by Django 3.1.7 on 2021-03-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0010_auto_20210321_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
