# Generated by Django 3.1.7 on 2021-03-22 02:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0011_auto_20210321_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
